version: '2'
services:
  node:
    image: node:10
    volumes:
      - ./:/app
    ports:
      - "12000:3000"
    working_dir: /app
    command: npm run dev
    environment:
      - MONGODB_URI=mongodb://mongo
      - MONGODB_DBNAME=goodjob-test
      - REDIS_URL=redis://redis
      - NODE_ENV=development
    # other variables, use .env
  mongo:
    image: mongo:3.6
    ports:
      - '27017:27017'
  redis:
    image: redis
